#!/bin/sh
# perfetto-fixture-qualify.sh qualifies gputrace Perfetto exports against a
# corpus of .gputrace fixtures and writes a durable validation receipt.
#
# For each fixture it exports canonical JSON, a lossless native trace, and a
# constrained native trace, then reconciles the canonical evidence report, the
# native evidence manifest, and the exporter-owned PerfettoSQL views against
# each other. It records every command, digest, and query result it relied on.
#
# Usage:
#   tools/perfetto-fixture-qualify.sh [--out DIR] [--max-output-bytes N] TRACE...
#
# The receipt is written to DIR/receipt.md (default ~/tmp/gputrace-perfetto-qualify).
# Exports stay in DIR; none of them belong in the repository.
set -eu

out=${GPUTRACE_QUALIFY_OUT:-$HOME/tmp/gputrace-perfetto-qualify}
budget=500000
while [ "$#" -gt 0 ]; do
	case "$1" in
	--out)
		[ "$#" -ge 2 ] || { echo "--out requires a directory" >&2; exit 2; }
		out=$2
		shift 2
		;;
	--max-output-bytes)
		[ "$#" -ge 2 ] || { echo "--max-output-bytes requires a value" >&2; exit 2; }
		budget=$2
		shift 2
		;;
	--)
		shift
		break
		;;
	*)
		break
		;;
	esac
done
[ "$#" -ge 1 ] || { echo "usage: $0 [--out DIR] [--max-output-bytes N] trace.gputrace..." >&2; exit 2; }

gputrace=${GPUTRACE:-gputrace}
command -v "$gputrace" >/dev/null || { echo "gputrace not found: $gputrace" >&2; exit 2; }
command -v jq >/dev/null || { echo "jq not found" >&2; exit 2; }
tp=${TRACE_PROCESSOR_SHELL:-$HOME/tmp/trace_processor_shell}
[ -x "$tp" ] || { echo "trace_processor_shell not found: $tp" >&2; exit 2; }
validate=$(dirname "$0")/perfetto-native-validate.sh
[ -f "$validate" ] || { echo "perfetto-native-validate.sh not found beside $0" >&2; exit 2; }

mkdir -p "$out"
receipt=$out/receipt.md
: > "$receipt"

digest() { shasum -a 256 "$1" | cut -d' ' -f1; }

# query runs one PerfettoSQL statement after the exporter-owned module and
# prints the single scalar it selects.
query() {
	{ cat "$2"; printf '%s\n' "$3"; } | "$tp" query "$1" 2>/dev/null | tail -1 | tr -d '"'
}

want() {
	name=$1 got=$2 expect=$3
	if [ "$got" != "$expect" ]; then
		printf '| %s | %s | %s | FAIL |\n' "$name" "$got" "$expect" >> "$receipt"
		echo "$name = $got, want $expect" >&2
		failed=$((failed + 1))
		return
	fi
	printf '| %s | %s | %s | ok |\n' "$name" "$got" "$expect" >> "$receipt"
}

failed=0
{
	echo "# gputrace Perfetto fixture qualification receipt"
	echo
	echo "Generated by \`tools/perfetto-fixture-qualify.sh\`. Every number below"
	echo "comes from the commands recorded with it; nothing here is asserted"
	echo "without a command that produced it."
	echo
	echo '```text'
	echo "gputrace version: $("$gputrace" version 2>&1 | head -1)"
	echo "trace_processor:  $tp"
	echo "trace_processor version: $("$tp" --version 2>&1 | head -1)"
	echo "constrained budget bytes: $budget"
	echo '```'
} >> "$receipt"

for trace in "$@"; do
	[ -e "$trace" ] || { echo "trace not found: $trace" >&2; exit 2; }
	name=$(basename "$trace" .gputrace)
	canon=$out/$name.json
	sql=$out/$name.sql
	lossless=$out/$name.pftrace
	lossless2=$out/$name.repeat.pftrace
	constrained=$out/$name.constrained.pftrace
	constrained2=$out/$name.constrained.repeat.pftrace

	{
		echo
		echo "## $name"
		echo
		echo '```text'
		echo "$gputrace timeline $trace --format json -o $canon"
		echo "$gputrace timeline $trace --format perfetto -o $lossless --sql-out $sql"
		echo "$gputrace timeline $trace --format perfetto -o $lossless2"
		echo "$gputrace timeline $trace --format perfetto --max-output-bytes $budget -o $constrained"
		echo "$gputrace timeline $trace --format perfetto --max-output-bytes $budget -o $constrained2"
		echo "sh $validate --sql $sql $lossless"
		echo "sh $validate --sql $sql $constrained"
		echo '```'
		echo
	} >> "$receipt"

	"$gputrace" timeline "$trace" --format json -o "$canon" >/dev/null
	"$gputrace" timeline "$trace" --format perfetto -o "$lossless" --sql-out "$sql" >/dev/null
	"$gputrace" timeline "$trace" --format perfetto -o "$lossless2" >/dev/null
	"$gputrace" timeline "$trace" --format perfetto --max-output-bytes "$budget" -o "$constrained" >/dev/null
	"$gputrace" timeline "$trace" --format perfetto --max-output-bytes "$budget" -o "$constrained2" >/dev/null

	{
		echo '```text'
		echo "input digest:       $(cd "$(dirname "$trace")" && find "$(basename "$trace")" -type f | LC_ALL=C sort | xargs shasum -a 256 | shasum -a 256 | cut -d' ' -f1)"
		echo "canonical digest:   $(digest "$canon")"
		echo "lossless digest:    $(digest "$lossless")"
		echo "constrained digest: $(digest "$constrained")"
		echo "SQL digest:         $(digest "$sql")"
		echo "lossless bytes:     $(wc -c < "$lossless" | tr -d ' ')"
		echo "constrained bytes:  $(wc -c < "$constrained" | tr -d ' ')"
		echo '```'
		echo
		echo "| check | value | expected | result |"
		echo "| --- | --- | --- | --- |"
	} >> "$receipt"

	sh "$validate" --sql "$sql" "$lossless" >/dev/null
	sh "$validate" --sql "$sql" "$constrained" >/dev/null
	want "external validator (lossless, constrained)" passed passed

	want "lossless export is byte stable" "$(digest "$lossless2")" "$(digest "$lossless")"
	want "constrained export is byte stable" "$(digest "$constrained2")" "$(digest "$constrained")"
	want "constrained export is within its byte boundary" \
		"$([ "$(wc -c < "$constrained")" -le "$budget" ] && echo yes || echo no)" yes

	source_dispatches=$(jq -r '.evidence_inventory.dispatches // 0' "$canon")
	source_encoders=$(jq -r '.evidence_inventory.encoders // 0' "$canon")

	# Source versus exported. The busy domain carries dispatches and encoders;
	# command buffers belong to the wall domain and are not compared here.
	want "manifest dispatch_count matches canonical JSON" \
		"$(query "$lossless" "$sql" "select cast(extract_arg(arg_set_id,'debug.dispatch_count') as int) from slice where name='gputrace evidence manifest';")" \
		"$source_dispatches"
	want "gputrace_dispatch rows match canonical JSON" \
		"$(query "$lossless" "$sql" 'select count(*) from gputrace_dispatch;')" \
		"$source_dispatches"
	want "manifest encoder_count matches canonical JSON" \
		"$(query "$lossless" "$sql" "select cast(extract_arg(arg_set_id,'debug.encoder_count') as int) from slice where name='gputrace evidence manifest';")" \
		"$source_encoders"
	want "gputrace_encoder rows match canonical JSON" \
		"$(query "$lossless" "$sql" 'select count(*) from gputrace_encoder;')" \
		"$source_encoders"

	# What the UI reads off these rows. The browser gate in
	# tools/perfetto-ui-smoke.sh proves the trace renders; these prove the rows
	# it renders are ordered and identified, which the UI cannot fix.
	want "encoder tracks out of numeric index order" \
		"$(query "$lossless" "$sql" "select count(*) from (select cast(substr(name, 9) as INT) as n, lag(cast(substr(name, 9) as INT)) over (order by id) as prev from track where name glob 'Encoder [0-9]*') where prev is not null and n <= prev;")" \
		0
	want "dispatches without a readable name" \
		"$(query "$lossless" "$sql" "select count(*) from gputrace_dispatch where name is null or name = '';")" \
		0
	want "dispatches without a stated pipeline identity" \
		"$(query "$lossless" "$sql" "select count(*) from gputrace_dispatch where coalesce(pipeline_identity_source,'') = '';")" \
		0

	# Untimed capture-only work must arrive as instants, never as heuristic
	# bars. A trace with measured GPU execution has no untimed dispatches.
	untimed=$(jq -r '.evidence_inventory.untimed_dispatches // 0' "$canon")
	if [ "$untimed" -gt 0 ]; then
		want "capture-only dispatches carry no duration" \
			"$(query "$lossless" "$sql" 'select count(*) from gputrace_dispatch where dur > 0;')" \
			0
		want "capture-only export claims no measured GPU slices" \
			"$(query "$lossless" "$sql" 'select count(*) from gpu_slice;')" \
			0
	fi

	# Parser health. The external validator already fails on errors and data
	# loss; this records the number the receipt claims.
	want "parser errors and data loss" \
		"$(query "$lossless" "$sql" "select coalesce(sum(value),0) from stats where value>0 and severity in ('error','data_loss');")" \
		0

	# Reference closure. Every retained dispatch must still resolve its encoder
	# and pipeline after a constrained export drops unrelated events.
	for export in "$lossless" "$constrained"; do
		label=lossless
		[ "$export" = "$constrained" ] && label=constrained
		want "$label dispatches with an unresolvable encoder" \
			"$(query "$export" "$sql" 'select count(*) from gputrace_dispatch d where d.encoder_id is not null and not exists(select 1 from gputrace_encoder e where e.encoder_id=d.encoder_id);')" \
			0
		want "$label dispatches with an unresolvable pipeline" \
			"$(query "$export" "$sql" 'select count(*) from gputrace_dispatch d where not exists(select 1 from gputrace_pipeline p where p.pipeline_state is d.pipeline_state and p.function_name is d.name);')" \
			0
		want "$label semantic links with an unresolvable node" \
			"$(query "$export" "$sql" 'select count(*) from gputrace_semantic_link l where not exists(select 1 from gputrace_semantic_node n where n.semantic_id=l.semantic_id);')" \
			0
	done

	# Loss totals. Retained plus dropped must account for everything
	# considered, and a lossless export must declare itself complete.
	want "lossless output_complete" \
		"$(query "$lossless" "$sql" "select cast(extract_arg(arg_set_id,'debug.output_complete') as int) from slice where name='gputrace evidence manifest';")" \
		1
	want "lossless events dropped" \
		"$(query "$lossless" "$sql" "select cast(extract_arg(arg_set_id,'debug.events_dropped') as int) from slice where name='gputrace evidence manifest';")" \
		0
	want "constrained loss totals reconcile" \
		"$(query "$constrained" "$sql" "select (select cast(extract_arg(arg_set_id,'debug.events_retained') as int) from slice where name='gputrace evidence manifest') + (select cast(extract_arg(arg_set_id,'debug.events_dropped') as int) from slice where name='gputrace evidence manifest') - (select cast(extract_arg(arg_set_id,'debug.events_considered') as int) from slice where name='gputrace evidence manifest');")" \
		0
	want "constrained export retains its manifest" \
		"$(query "$constrained" "$sql" "select count(*) from gputrace_manifest_arg where key='output_complete';")" \
		1
done

{
	echo
	if [ "$failed" -eq 0 ]; then
		echo "All fixture qualification checks passed."
	else
		echo "$failed fixture qualification checks FAILED."
	fi
} >> "$receipt"

echo "wrote $receipt"
[ "$failed" -eq 0 ] || exit 1
