#!/bin/bash
# perfetto-reference.sh extracts the structure of two published Perfetto traces
# and of our own export, for side-by-side comparison.
#
# The reference traces are binary protobuf, 21 MB and 58 MB. They are not
# uploaded to the notebook and should not be: a language model cannot read
# protobuf, so 80 MB of it is pure noise. What is useful is the shape --
# how many tracks, how deep slices nest, what track types a real trace uses --
# and that is what this writes out.
#
# Usage: tools/perfetto-reference.sh [outdir]
set -euo pipefail

OUT="${1:-$HOME/tmp/gputrace-perfetto-reference}"
CACHE="$HOME/tmp"
TP="$CACHE/trace_processor_shell"
OURS="$HOME/tmp/gputrace-nlm-corpus/perfetto/timeline-perfetto.json"

CHROME_URL=https://storage.googleapis.com/perfetto-misc/chrome_example_wikipedia.perfetto_trace.gz
ANDROID_URL=https://storage.googleapis.com/perfetto-misc/example_android_trace

mkdir -p "$OUT"
[ -x "$TP" ] || { curl -sL -o "$TP" https://get.perfetto.dev/trace_processor; chmod +x "$TP"; }
[ -e "$CACHE/$(basename $CHROME_URL)" ]  || curl -sL -o "$CACHE/$(basename $CHROME_URL)"  "$CHROME_URL"
[ -e "$CACHE/$(basename $ANDROID_URL)" ] || curl -sL -o "$CACHE/$(basename $ANDROID_URL)" "$ANDROID_URL"

q() { printf '%s\n' "$1" > "$CACHE/.q.sql"; "$TP" -q "$CACHE/.q.sql" "$2" 2>/dev/null | sed -n '/^"/,$p'; }

TOTALS="select 'slices' as k, count(*) as v from slice
union all select 'counters',count(*) from counter
union all select 'tracks',count(*) from track
union all select 'processes',count(*) from process
union all select 'threads',count(*) from thread;"
DEPTH="select depth, count(*) as slices from slice group by 1 order by 1 limit 12;"
ERRORS="select name, value from stats where value>0 and severity in ('error','data_loss') limit 20;"

{
	echo "# Perfetto reference structure (trace_processor $("$TP" --version 2>&1 | head -1))"
	echo
	echo "Generated by tools/perfetto-reference.sh. Reference traces:"
	echo "  $CHROME_URL"
	echo "  $ANDROID_URL"
	echo
	echo "The traces are binary protobuf and are not uploaded. Only this shape is."
	echo
	for t in "$CACHE/$(basename $CHROME_URL)" "$CACHE/$(basename $ANDROID_URL)" "$OURS"; do
		echo "## $(basename "$t")"
		echo '### totals';       q "$TOTALS" "$t"
		echo '### slice depth';  q "$DEPTH"  "$t"
		echo '### errors';       q "$ERRORS" "$t"
		echo
	done
} > "$OUT/perfetto-reference-structure.md"

echo "wrote $OUT/perfetto-reference-structure.md"
